version: '3'
services:
  mongo:
    image: mongo:4.0.5
    container_name: mongo-container
    volumes:
      - ./volumes/mongo/db:/data/db
      - ./volumes/mongo/log:/var/log/mongodb/
      - ./mongo-dump:/docker-entrypoint-initdb.d/dump
      - ./mongo-setup.sh:/docker-entrypoint-initdb.d/mongo-setup.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_HOST: 127.0.0.1
      MONGO_PORT: 27017
    ports:
      - 27017:27017